[project]
name = "ksmyvoteinfo"
version = "1.8.2"
description = "Query the KS SOS site for voter registration"
authors = [
    {name = "Peter Karman", email = "peter@peknet.com"},
]
dependencies = [
    "beautifulsoup4",
    "python-dateutil",
    "requests",
    "Werkzeug",
]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "http://github.com/BlueprintKansas/ksmyvoteinfo-py"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
