on:
  pull_request:
  push:
    branches:
      - master

name: Test and Lint
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.18, 3.11.13, 3.12.11]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dev Dependencies
        run: make deps
      - name: Lint
        run: make lint
      - name: Test
        run: make test
